// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: TransactionPB.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct TransactionPB {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var hash: String = String()

  var address: String = String()

  var contractAddress: String = String()

  var type: String = String()

  var balance: String = String()

  var delta: String = String()

  var from: String = String()

  var to: String = String()

  var blockHash: String = String()

  var blockNumber: Int32 = 0

  var status: String = String()

  var timestamp: String = String()

  var nonce: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension TransactionPB: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "TransactionPB"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "hash"),
    2: .same(proto: "address"),
    3: .standard(proto: "contract_address"),
    4: .same(proto: "type"),
    5: .same(proto: "balance"),
    6: .same(proto: "delta"),
    7: .same(proto: "from"),
    8: .same(proto: "to"),
    9: .standard(proto: "block_hash"),
    10: .standard(proto: "block_number"),
    11: .same(proto: "status"),
    12: .same(proto: "timestamp"),
    13: .same(proto: "nonce"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.hash) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.address) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.contractAddress) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.balance) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.delta) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.from) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.to) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.blockHash) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self.blockNumber) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.timestamp) }()
      case 13: try { try decoder.decodeSingularInt32Field(value: &self.nonce) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.hash.isEmpty {
      try visitor.visitSingularStringField(value: self.hash, fieldNumber: 1)
    }
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 2)
    }
    if !self.contractAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.contractAddress, fieldNumber: 3)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 4)
    }
    if !self.balance.isEmpty {
      try visitor.visitSingularStringField(value: self.balance, fieldNumber: 5)
    }
    if !self.delta.isEmpty {
      try visitor.visitSingularStringField(value: self.delta, fieldNumber: 6)
    }
    if !self.from.isEmpty {
      try visitor.visitSingularStringField(value: self.from, fieldNumber: 7)
    }
    if !self.to.isEmpty {
      try visitor.visitSingularStringField(value: self.to, fieldNumber: 8)
    }
    if !self.blockHash.isEmpty {
      try visitor.visitSingularStringField(value: self.blockHash, fieldNumber: 9)
    }
    if self.blockNumber != 0 {
      try visitor.visitSingularInt32Field(value: self.blockNumber, fieldNumber: 10)
    }
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 11)
    }
    if !self.timestamp.isEmpty {
      try visitor.visitSingularStringField(value: self.timestamp, fieldNumber: 12)
    }
    if self.nonce != 0 {
      try visitor.visitSingularInt32Field(value: self.nonce, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TransactionPB, rhs: TransactionPB) -> Bool {
    if lhs.hash != rhs.hash {return false}
    if lhs.address != rhs.address {return false}
    if lhs.contractAddress != rhs.contractAddress {return false}
    if lhs.type != rhs.type {return false}
    if lhs.balance != rhs.balance {return false}
    if lhs.delta != rhs.delta {return false}
    if lhs.from != rhs.from {return false}
    if lhs.to != rhs.to {return false}
    if lhs.blockHash != rhs.blockHash {return false}
    if lhs.blockNumber != rhs.blockNumber {return false}
    if lhs.status != rhs.status {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.nonce != rhs.nonce {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
